services:
  prowlarr:
    container_name: servarr-prowlarr
    image: ghcr.io/hotio/prowlarr
    restart: unless-stopped
    networks:
      - servarr
      - proxy
      - metrics
    labels:
      traefik.enable: true
      traefik.http.routers.prowlarr.rule: Host(`prowlarr`)
    environment:
      PUID: 991
      PGID: 994
      UMASK: 002
      TZ: Europe/London
    volumes:
      - /containers/servarr-prowlarr:/config

  radarr:
    container_name: servarr-radarr
    image: ghcr.io/hotio/radarr
    restart: unless-stopped
    networks:
      - servarr
      - proxy
      - metrics
    labels:
      traefik.enable: true
      traefik.http.routers.radarr.rule: Host(`radarr`)
    environment:
      PUID: 991
      PGID: 994
      UMASK: 002
      TZ: Europe/London
    volumes:
      - /containers/servarr-radarr:/config
      - /downloads:/downloads
      - /tank/media/movies:/tank/media/movies

  sonarr:
    container_name: servarr-sonarr
    image: ghcr.io/hotio/sonarr
    restart: unless-stopped
    networks:
      - servarr
      - proxy
      - metrics
    labels:
      traefik.enable: true
      traefik.http.routers.sonarr.rule: Host(`sonarr`)
    environment:
      PUID: 991
      PGID: 994
      UMASK: 002
      TZ: Europe/London
    volumes:
      - /containers/servarr-sonarr:/config
      - /downloads:/downloads
      - /tank/media/tv:/tank/media/tv
      - /tank/media/sport:/tank/media/sport

  lidarr:
    container_name: servarr-lidarr
    image: ghcr.io/hotio/lidarr
    restart: unless-stopped
    networks:
      - servarr
      - proxy
      - metrics
    labels:
      traefik.enable: true
      traefik.http.routers.lidarr.rule: Host(`lidarr`)
    environment:
      PUID: 991
      PGID: 994
      UMASK: 002
      TZ: Europe/London
    volumes:
      - /containers/servarr-lidarr:/config
      - /downloads:/downloads
      - /tank/media/music:/tank/media/music

  whisparr:
    container_name: servarr-whisparr
    image: ghcr.io/hotio/whisparr
    restart: unless-stopped
    networks:
      - servarr
      - proxy
      - metrics
    labels:
      traefik.enable: true
      traefik.http.routers.whisparr.rule: Host(`whisparr`)
    environment:
      PUID: 991
      PGID: 994
      UMASK: 002
      TZ: Europe/London
    volumes:
      - /containers/servarr-whisparr:/config
      - /downloads:/downloads
      - /tank/media/xxx/videos:/tank/media/xxx/videos

networks:
  proxy:
    external: true
  metrics:
    external: true
  servarr:
    name: servarr
    enable_ipv6: true
