version: "3"

services:
  prowlarr:
    image: cr.hotio.dev/hotio/prowlarr
    container_name: prowlarr
    restart: unless-stopped
    ports:
      - 9696:9696
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/London
    volumes:
      - prowlarr:/config

  radarr:
    container_name: radarr
    image: cr.hotio.dev/hotio/radarr
    restart: unless-stopped
    ports:
      - "7878:7878"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/London
    volumes:
      - radarr:/config
      - /tank:/tank

volumes:
  prowlarr:
  radarr:
