version: '3'

services:
  prowlarr:
    image: ghcr.io/hotio/prowlarr
    container_name: prowlarr
    restart: unless-stopped
    ports:
      - 9696:9696
    environment:
      PUID: 1000
      PGID: 1000
      UMASK: 002
      TZ: Europe/London
    volumes:
      - prowlarr:/config

  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr
    restart: unless-stopped
    ports:
      - 7878:7878
    environment:
      PUID: 1000
      PGID: 1000
      UMASK: 002
      TZ: Europe/London
    volumes:
      - radarr:/config
      - /tank:/tank

  sonarr:
    image: ghcr.io/hotio/sonarr
    container_name: sonarr
    restart: unless-stopped
    ports:
      - 8989:8989
    environment:
      PUID: 1000
      PGID: 1000
      UMASK: 002
      TZ: Europe/London
    volumes:
      - sonarr:/config
      - /tank:/tank

  lidarr:
    container_name: lidarr
    image: ghcr.io/hotio/lidarr
    restart: unless-stopped
    ports:
      - 8686:8686
    environment:
      PUID: 1000
      PGID: 1000
      UMASK: 002
      TZ: Europe/London
    volumes:
      - lidarr:/config
      - /tank:/tank

  whisparr:
    container_name: whisparr
    image: ghcr.io/hotio/whisparr
    restart: unless-stopped
    ports:
      - 6969:6969
    environment:
      PUID: 1000
      PGID: 1000
      UMASK: 002
      TZ: Europe/London
    volumes:
      - whisparr:/config
      - /tank:/tank

  bazarr:
    container_name: bazarr
    image: ghcr.io/hotio/bazarr
    restart: unless-stopped
    ports:
      - 6767:6767
    environment:
      PUID: 1000
      PGID: 1000
      UMASK: 002
      TZ: Europe/London
    volumes:
      - bazarr:/config
      - /tank:/tank

volumes:
  prowlarr:
  radarr:
  sonarr:
  lidarr:
  whisparr:
  bazarr:
