version: "3"

services:
  prowlarr:
    image: cr.hotio.dev/hotio/prowlarr
    container_name: prowlarr
    restart: unless-stopped
    ports:
      - 9696:9696
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/London
    volumes:
      - prowlarr:/config

volumes:
  prowlarr:
