version: '3'

services:
  prowlarr:
    image: ghcr.io/hotio/prowlarr
    container_name: prowlarr
    restart: unless-stopped
    network_mode: host
    ports:
      - 9696:9696
    labels:
      traefik.enable: true
      traefik.http.services.prowlarr.loadbalancer.server.port: 9696
      traefik.http.routers.prowlarr.rule: Host(`prowlarr`)
    environment:
      PUID: 1000
      PGID: 1000
      UMASK: 002
      TZ: Europe/London
    volumes:
      - /containers/prowlarr:/config

  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr
    restart: unless-stopped
    network_mode: host
    ports:
      - 7878:7878
    labels:
      traefik.enable: true
      traefik.http.services.radarr.loadbalancer.server.port: 7878
      traefik.http.routers.radarr.rule: Host(`radarr`)
    environment:
      PUID: 1000
      PGID: 1000
      UMASK: 002
      TZ: Europe/London
    volumes:
      - /containers/radarr:/config
      - /tank/media/movies:/tank/media/movies

  sonarr:
    image: ghcr.io/hotio/sonarr
    container_name: sonarr
    restart: unless-stopped
    network_mode: host
    ports:
      - 8989:8989
    labels:
      traefik.enable: true
      traefik.http.services.sonarr.loadbalancer.server.port: 8989
      traefik.http.routers.sonarr.rule: Host(`sonarr`)
    environment:
      PUID: 1000
      PGID: 1000
      UMASK: 002
      TZ: Europe/London
    volumes:
      - /containers/sonarr:/config
      - /tank/media/tv:/tank/media/tv
      - /tank/media/sport:/tank/media/sport

  lidarr:
    container_name: lidarr
    image: ghcr.io/hotio/lidarr
    restart: unless-stopped
    network_mode: host
    ports:
      - 8686:8686
    labels:
      traefik.enable: true
      traefik.http.services.lidarr.loadbalancer.server.port: 8686
      traefik.http.routers.lidarr.rule: Host(`lidarr`)
    environment:
      PUID: 1000
      PGID: 1000
      UMASK: 002
      TZ: Europe/London
    volumes:
      - /containers/lidarr:/config
      - /tank/media/music:/tank/media/music
