services:
  prowlarr:
    container_name: servarr-prowlarr
    image: ghcr.io/hotio/prowlarr
    restart: unless-stopped
    networks:
      - default
      - proxy
      - metrics
    labels:
      traefik.enable: true
      traefik.http.routers.prowlarr.rule: Host(`prowlarr`)
      traefik.http.routers.prowlarr.middlewares: trusted-ipallowlist, authentik
    environment:
      PUID: 991
      PGID: 994
      UMASK: 002
      TZ: Europe/London
    volumes:
      - /containers/servarr-prowlarr:/config

  radarr:
    container_name: servarr-radarr
    image: ghcr.io/hotio/radarr
    restart: unless-stopped
    networks:
      - default
      - proxy
      - metrics
    labels:
      traefik.enable: true
      traefik.http.routers.radarr.rule: Host(`radarr`)
      traefik.http.routers.radarr.middlewares: trusted-ipallowlist, authentik
    environment:
      PUID: 991
      PGID: 994
      UMASK: 002
      TZ: Europe/London
    volumes:
      - /containers/servarr-radarr:/config
      - /downloads:/downloads
      - /tank/media/movies:/tank/media/movies

  sonarr:
    container_name: servarr-sonarr
    image: ghcr.io/hotio/sonarr
    restart: unless-stopped
    networks:
      - default
      - proxy
      - metrics
    labels:
      traefik.enable: true
      traefik.http.routers.sonarr.rule: Host(`sonarr`)
      traefik.http.routers.sonarr.middlewares: trusted-ipallowlist, authentik
    environment:
      PUID: 991
      PGID: 994
      UMASK: 002
      TZ: Europe/London
    volumes:
      - /containers/servarr-sonarr:/config
      - /downloads:/downloads
      - /tank/media/tv:/tank/media/tv
      - /tank/media/sport:/tank/media/sport

  lidarr:
    container_name: servarr-lidarr
    image: ghcr.io/hotio/lidarr
    restart: unless-stopped
    networks:
      - default
      - proxy
      - metrics
    labels:
      traefik.enable: true
      traefik.http.routers.lidarr.rule: Host(`lidarr`)
      traefik.http.routers.lidarr.middlewares: trusted-ipallowlist, authentik
    environment:
      PUID: 991
      PGID: 994
      UMASK: 002
      TZ: Europe/London
    volumes:
      - /containers/servarr-lidarr:/config
      - /downloads:/downloads
      - /tank/media/music:/tank/media/music

  whisparr:
    container_name: servarr-whisparr
    image: ghcr.io/hotio/whisparr:v3
    restart: unless-stopped
    networks:
      - default
      - proxy
      - metrics
    labels:
      traefik.enable: true
      traefik.http.routers.whisparr.rule: Host(`whisparr`)
      traefik.http.routers.whisparr.middlewares: trusted-ipallowlist, authentik
    environment:
      PUID: 991
      PGID: 994
      UMASK: 002
      TZ: Europe/London
    volumes:
      - /containers/servarr-whisparr:/config
      - /downloads:/downloads
      - /tank/media/xxx/import:/tank/media/xxx/import
      - /tank/media/xxx/movies:/tank/media/xxx/movies
      - /tank/media/xxx/scenes:/tank/media/xxx/scenes

  qbittorrent:
    container_name: servarr-qbittorrent
    image: ghcr.io/hotio/qbittorrent
    restart: unless-stopped
    ports:
      - 58261:58261     # BitTorrent port. Needs port forwarding to be setup on the router.
      - 58261:58261/udp # BitTorrent port. Needs port forwarding to be setup on the router.
    networks:
      - default
      - proxy
    environment:
      PUID: 991
      PGID: 994
      UMASK: 002
      TZ: Europe/London
    labels:
      traefik.enable: true
      traefik.http.routers.qbittorrent.rule: Host(`qbittorrent`)
      traefik.http.routers.qbittorrent.middlewares: trusted-ipallowlist, authentik
    volumes:
      - /containers/servarr-qbittorrent:/config
      - /downloads:/downloads

  sabnzbd:
    container_name: servarr-sabnzbd
    image: ghcr.io/hotio/sabnzbd
    restart: unless-stopped
    networks:
      - default
      - proxy
      - metrics
    environment:
      PUID: 991
      PGID: 994
      UMASK: 002
      TZ: Europe/London
    labels:
      traefik.enable: true
      traefik.http.routers.sabnzbd.rule: Host(`sabnzbd`)
      traefik.http.routers.sabnzbd.middlewares: trusted-ipallowlist, authentik
    volumes:
      - /containers/servarr-sabnzbd:/config
      - /downloads:/downloads

  tdarr:
    image: ghcr.io/haveagitgat/tdarr
    container_name: servarr-tdarr
    restart: unless-stopped
    networks:
      proxy:
      metrics:
    environment:
      PUID: 991 # media user
      PGID: 994 # media group
      TZ: Europe/London
      UMASK_SET: 002
      internalNode: true
      nodeName: Server
    labels:
      traefik.enable: true
      traefik.http.routers.tdarr.rule: Host(`tdarr`)
      traefik.http.routers.tdarr.middlewares: trusted-ipallowlist, authentik
    volumes:
      - /containers/servarr-tdarr/configs:/app/configs
      - /containers/servarr-tdarr/logs:/app/logs
      - /containers/servarr-tdarr/server:/app/server
      - /var/tmp/tdarr:/work # "Transcode Cache" - Should be excluded from snapshots
      - /tank/media/movies:/tank/media/movies
      - /tank/media/tv:/tank/media/tv
      - /tank/media/xxx/scenes:/tank/media/xxx/scenes
    devices:
      - /dev/dri:/dev/dri

networks:
  default:
    name: servarr
    enable_ipv6: true
  metrics:
    external: true
  proxy:
    external: true
