services:
  prowlarr:
    image: ghcr.io/hotio/prowlarr
    container_name: prowlarr
    restart: unless-stopped
    network_mode: host
    ports:
      - 9696:9696
    labels:
      traefik.enable: true
      traefik.http.services.prowlarr.loadbalancer.server.port: 9696
      traefik.http.routers.prowlarr.rule: Host(`prowlarr`)
      traefik.http.routers.prowlarr.middlewares: prowlarr-ipallowlist
      traefik.http.middlewares.prowlarr-ipallowlist.ipallowlist.sourcerange: >
        2a00:23c8:bda0:b310::/64,
        2a00:23c8:bda0:b311::/64,
        10.10.0.0/16,
        10.11.0.0/16
    environment:
      PUID: 991
      PGID: 994
      UMASK: 002
      TZ: Europe/London
    volumes:
      - /containers/prowlarr:/config

  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr
    restart: unless-stopped
    network_mode: host
    ports:
      - 7878:7878
    labels:
      traefik.enable: true
      traefik.http.services.radarr.loadbalancer.server.port: 7878
      traefik.http.routers.radarr.rule: Host(`radarr`)
      traefik.http.routers.radarr.middlewares: radarr-ipallowlist
      traefik.http.middlewares.radarr-ipallowlist.ipallowlist.sourcerange: >
        2a00:23c8:bda0:b310::/64,
        2a00:23c8:bda0:b311::/64,
        10.10.0.0/16,
        10.11.0.0/16
    environment:
      PUID: 991
      PGID: 994
      UMASK: 002
      TZ: Europe/London
    volumes:
      - /containers/radarr:/config
      - /downloads:/downloads
      - /tank/media/movies:/tank/media/movies

  sonarr:
    image: ghcr.io/hotio/sonarr
    container_name: sonarr
    restart: unless-stopped
    network_mode: host
    ports:
      - 8989:8989
    labels:
      traefik.enable: true
      traefik.http.services.sonarr.loadbalancer.server.port: 8989
      traefik.http.routers.sonarr.rule: Host(`sonarr`)
      traefik.http.routers.sonarr.middlewares: sonarr-ipallowlist
      traefik.http.middlewares.sonarr-ipallowlist.ipallowlist.sourcerange: >
        2a00:23c8:bda0:b310::/64,
        2a00:23c8:bda0:b311::/64,
        10.10.0.0/16,
        10.11.0.0/16
    environment:
      PUID: 991
      PGID: 994
      UMASK: 002
      TZ: Europe/London
    volumes:
      - /containers/sonarr:/config
      - /downloads:/downloads
      - /tank/media/tv:/tank/media/tv
      - /tank/media/sport:/tank/media/sport

  lidarr:
    container_name: lidarr
    image: ghcr.io/hotio/lidarr
    restart: unless-stopped
    network_mode: host
    ports:
      - 8686:8686
    labels:
      traefik.enable: true
      traefik.http.services.lidarr.loadbalancer.server.port: 8686
      traefik.http.routers.lidarr.rule: Host(`lidarr`)
      traefik.http.routers.lidarr.middlewares: lidarr-ipallowlist
      traefik.http.middlewares.lidarr-ipallowlist.ipallowlist.sourcerange: >
        2a00:23c8:bda0:b310::/64,
        2a00:23c8:bda0:b311::/64,
        10.10.0.0/16,
        10.11.0.0/16
    environment:
      PUID: 991
      PGID: 994
      UMASK: 002
      TZ: Europe/London
    volumes:
      - /containers/lidarr:/config
      - /downloads:/downloads
      - /tank/media/music:/tank/media/music

  whisparr:
    container_name: whisparr
    image: ghcr.io/hotio/whisparr
    restart: unless-stopped
    network_mode: host
    ports:
      - 6969:6969
    labels:
      traefik.enable: true
      traefik.http.services.whisparr.loadbalancer.server.port: 6969
      traefik.http.routers.whisparr.rule: Host(`whisparr`)
      traefik.http.routers.whisparr.middlewares: whisparr-ipallowlist
      traefik.http.middlewares.whisparr-ipallowlist.ipallowlist.sourcerange: >
        2a00:23c8:bda0:b310::/64,
        10.10.0.0/16
    environment:
      PUID: 991
      PGID: 994
      UMASK: 002
      TZ: Europe/London
    volumes:
      - /containers/whisparr:/config
      - /downloads:/downloads
      - /tank/media/xxx/videos:/tank/media/xxx/videos
