version: '3'

services:
  prowlarr:
    image: ghcr.io/hotio/prowlarr
    container_name: prowlarr
    restart: unless-stopped
    ports:
      - 9696:9696
    environment:
      PUID: 1000
      PGID: 1000
      UMASK: 002
      TZ: Europe/London
    volumes:
      - /tank/docker/prowlarr:/config

  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr
    restart: unless-stopped
    ports:
      - 7878:7878
    environment:
      PUID: 1000
      PGID: 1000
      UMASK: 002
      TZ: Europe/London
    volumes:
      - /tank/docker/radarr:/config
      - /tank:/tank

  sonarr:
    image: ghcr.io/hotio/sonarr
    container_name: sonarr
    restart: unless-stopped
    ports:
      - 8989:8989
    environment:
      PUID: 1000
      PGID: 1000
      UMASK: 002
      TZ: Europe/London
    volumes:
      - /tank/docker/sonarr:/config
      - /tank:/tank

  lidarr:
    container_name: lidarr
    image: ghcr.io/hotio/lidarr
    restart: unless-stopped
    ports:
      - 8686:8686
    environment:
      PUID: 1000
      PGID: 1000
      UMASK: 002
      TZ: Europe/London
    volumes:
      - /tank/docker/lidarr:/config
      - /tank:/tank

  whisparr:
    container_name: whisparr
    image: ghcr.io/hotio/whisparr
    restart: unless-stopped
    ports:
      - 6969:6969
    environment:
      PUID: 1000
      PGID: 1000
      UMASK: 002
      TZ: Europe/London
    volumes:
      - /tank/docker/whisparr:/config
      - /tank:/tank

  bazarr:
    container_name: bazarr
    image: ghcr.io/hotio/bazarr
    restart: unless-stopped
    ports:
      - 6767:6767
    environment:
      PUID: 1000
      PGID: 1000
      UMASK: 002
      TZ: Europe/London
    volumes:
      - /tank/docker/bazarr:/config
      - /tank:/tank
